# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20190316_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
